import = ["/Users/devonlin101/.alacritty-colorscheme/themes/everforest.yaml"]

#[Cursor]
#blink_interval = 750
#blink_timeout = 5
#blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "VictorMono NFM semibold"
style = "Bold"

[font.italic]
family = "VictorMono NFM SemiBold"
style = "Italic"

[font.normal]
family = "VictorMono NFM semibold"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
dynamic_title = true
